#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep  5 17:07:11 2019

@author: israel
"""

import os, fnmatch
import pandas as pd
from openpyxl import load_workbook

# Open function to open the file "MyFile1.txt"  
# (same directory) in append mode and 
fbe_files = fnmatch.filter(sorted(os.listdir("./FBE LSU EXP1/")), '*.fbe')

drow1 = []
drow2 = []
drow3 = []
drow4 = []
drow5 = []
drow6 = []
drow7 = []
drow8 = []


for file_name in fbe_files:
 
   first = True 
   f = open("./FBE LSU EXP1/"+file_name, "r")
   print(file_name)

   for x in f:
     
     if "data id=" in x:
      
        t = x.split(',')
        
        depth = t[0]
        depth = depth[t[0].find('>')+1:]
        
        if float(depth)<0:
           continue
        
        drow1.append(t[1])
        drow2.append(t[2])
        drow3.append(t[3])
        drow4.append(t[4])
        drow5.append(t[5])
        drow6.append(t[6])
        drow7.append(t[7])
     
        tt = t[8].split('<')
        drow8.append(tt[0])
        
     if "</logData>" in x:
        del drow1[-1]
        del drow2[-1]
        del drow3[-1]
        del drow4[-1]
        del drow5[-1]
        del drow6[-1]
        del drow7[-1]
        del drow8[-1]
     
   ## END FOR file_name

#File 1   
output_file = "./FBE LSU EXP1/"+"SF00-5000" +'.xlsx'
output_df = pd.DataFrame(drow1) 
writer = pd.ExcelWriter(output_file)
output_df.to_excel(writer)       
writer.save()
writer.close()

#File 2   
output_file = "./FBE LSU EXP1/"+"SF02-10" +'.xlsx'     
output_df = pd.DataFrame(drow2,index=range(0,len(drow2)),columns=['1'])
writer = pd.ExcelWriter(output_file)
output_df.to_excel(writer)       
writer.save()
writer.close()

#File 3   
output_file = "./FBE LSU EXP1/"+"SF10-50" +'.xlsx'     
output_df = pd.DataFrame(drow3,index=range(0,len(drow3)),columns=['1'])
writer = pd.ExcelWriter(output_file)
output_df.to_excel(writer)       
writer.save()
writer.close()

#File 4   
output_file = "./FBE LSU EXP1/"+"SF50-200" +'.xlsx'     
output_df = pd.DataFrame(drow4,index=range(0,len(drow4)),columns=['1'])
writer = pd.ExcelWriter(output_file)
output_df.to_excel(writer)       
writer.save()
writer.close()

#File 5   
output_file = "./FBE LSU EXP1/"+"SF200-500" +'.xlsx'     
output_df = pd.DataFrame(drow5,index=range(0,len(drow5)),columns=['1'])
writer = pd.ExcelWriter(output_file)
output_df.to_excel(writer)       
writer.save()
writer.close() 

#File 6   
output_file = "./FBE LSU EXP1/"+"SF500-1000" +'.xlsx'     
output_df = pd.DataFrame(drow6,index=range(0,len(drow6)),columns=['1'])
writer = pd.ExcelWriter(output_file)
output_df.to_excel(writer)       
writer.save()
writer.close() 

#File 7   
output_file = "./FBE LSU EXP1/"+"SF1000-2500" +'.xlsx'     
output_df = pd.DataFrame(drow7,index=range(0,len(drow7)),columns=['1'])
writer = pd.ExcelWriter(output_file)
output_df.to_excel(writer)       
writer.save()
writer.close() 

#File 8   
output_file = "./FBE LSU EXP1/"+"SF2500-5000" +'.xlsx'     
output_df = pd.DataFrame(drow8,index=range(0,len(drow8)),columns=['1'])
writer = pd.ExcelWriter(output_file)
output_df.to_excel(writer)       
writer.save()
writer.close() 

## END FOR fbe_files   
